import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import './globals.css';
// import { Inter } from 'next/font/google'
// const inter = Inter({ subsets: ['latin'] });
// import { cn } from '../@/lib/utils';
import { cn } from '@/lib/utils';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className} */}
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
