/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/6al8npvpb20
 */
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"

export function DashBoard() {
  return (
    <main className="flex-1 overflow-x-hidden overflow-y-auto bg-gray-50 dark:bg-gray-900 p-6">
      <h1 className="text-3xl font-semibold text-gray-700 dark:text-gray-200">Dashboard</h1>
      <div className="grid gap-6 mt-8 lg:grid-cols-2 xl:grid-cols-4">
        <Card>
          <CardHeader className="pb-4">
            <CardTitle className="text-sm font-medium">Sales</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-4xl font-semibold text-gray-700 dark:text-gray-200">2,345</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-4">
            <CardTitle className="text-sm font-medium">Visitors</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-4xl font-semibold text-gray-700 dark:text-gray-200">8,765</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-4">
            <CardTitle className="text-sm font-medium">Reports</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-4xl font-semibold text-gray-700 dark:text-gray-200">123</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-4">
            <CardTitle className="text-sm font-medium">Settings</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-4xl font-semibold text-gray-700 dark:text-gray-200">999</p>
          </CardContent>
        </Card>
      </div>
      <div className="grid gap-6 mt-8 lg:grid-cols-2">
        <Card>
          <CardHeader className="pb-4">
            <CardTitle className="text-sm font-medium">Sales Line Graph</CardTitle>
          </CardHeader>
          <CardContent>
            <img
              alt="Sales Line Graph"
              height="300"
              src="/placeholder.svg"
              style={{
                aspectRatio: "500/300",
                objectFit: "cover",
              }}
              width="500"
            />
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-4">
            <CardTitle className="text-sm font-medium">Visitors Bar Chart (12 months)</CardTitle>
          </CardHeader>
          <CardContent>
            <img
              alt="Visitors Bar Chart"
              height="300"
              src="/placeholder.svg"
              style={{
                aspectRatio: "500/300",
                objectFit: "cover",
              }}
              width="500"
            />
          </CardContent>
        </Card>
      </div>
      <div className="mt-8">
        <Card>
          <CardHeader className="pb-4">
            <CardTitle className="text-sm font-medium">Project Information</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                <thead className="bg-gray-50 dark:bg-gray-800">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">
                      Project Name
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">
                      Status
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">
                      Start Date
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">
                      End Date
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-300 uppercase tracking-wider">
                      Budget
                    </th>
                  </tr>
                </thead>
                <tbody className="bg-white dark:bg-gray-900 divide-y divide-gray-200 dark:divide-gray-700">
                  <tr>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-300">Project A</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-300">
                      In Progress
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-300">01/01/2023</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-300">12/31/2023</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-300">
                      <div className="w-full bg-gray-200 dark:bg-gray-700 rounded relative group">
                        <div
                          className="h-2 bg-green-500 dark:bg-green-400 rounded"
                          style={{
                            width: "50%",
                          }}
                        />
                        <span className="absolute top-0 right-0 transform translate-x-1/2 -translate-y-1/2 bg-white dark:bg-gray-800 text-xs px-2 py-1 rounded group-hover:opacity-100 opacity-0 transition-opacity">
                          50%
                        </span>
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-300">Project B</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-300">Completed</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-300">01/01/2022</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-300">12/31/2022</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-gray-300">
                      <div className="w-full bg-gray-200 dark:bg-gray-700 rounded relative group">
                        <div
                          className="h-2 bg-green-500 dark:bg-green-400 rounded"
                          style={{
                            width: "100%",
                          }}
                        />
                        <span className="absolute top-0 right-0 transform translate-x-1/2 -translate-y-1/2 bg-white dark:bg-gray-800 text-xs px-2 py-1 rounded group-hover:opacity-100 opacity-0 transition-opacity">
                          100%
                        </span>
                      </div>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </CardContent>
        </Card>
      </div>
    </main>
  )
}
