/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/n4OLoInqtuB
 */
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { PopoverTrigger, PopoverContent, Popover } from "@/components/ui/popover"
import { Button } from "@/components/ui/button"

export function InvoiceTable() {
  return (
    <div className="border rounded-lg w-full">
      <div className="relative w-full overflow-auto">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="w-[100px] cursor-pointer hover:bg-gray-200 dark:hover:bg-gray-800">ID</TableHead>
              <TableHead className="cursor-pointer hover:bg-gray-200 dark:hover:bg-gray-800">Invoice Date</TableHead>
              <TableHead className="cursor-pointer hover:bg-gray-200 dark:hover:bg-gray-800">Due Date</TableHead>
              <TableHead className="cursor-pointer hover:bg-gray-200 dark:hover:bg-gray-800">Status</TableHead>
              <TableHead className="text-right cursor-pointer hover:bg-gray-200 dark:hover:bg-gray-800">
                Amount
              </TableHead>
              <TableHead className="text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableCell className="font-medium">INV001</TableCell>
              <TableCell>01/01/2023</TableCell>
              <TableCell>05/01/2023</TableCell>
              <TableCell>
                <span className="inline-block bg-green-200 text-green-800 px-2 py-1 rounded-full text-xs font-medium dark:bg-green-700 dark:text-green-200">
                  Paid
                </span>
              </TableCell>
              <TableCell className="text-right">
                <input
                  className="border rounded-md p-1 text-right dark:bg-gray-800 dark:text-gray-200"
                  defaultValue="$250.00"
                  type="text"
                />
              </TableCell>
              <TableCell className="text-right">
                <Popover>
                  <PopoverTrigger>
                    <svg
                      className=" h-5 w-5 text-gray-500 hover:text-gray-700 dark:hover:text-gray-300"
                      fill="none"
                      height="24"
                      stroke="currentColor"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      viewBox="0 0 24 24"
                      width="24"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <circle cx="12.1" cy="12.1" r="1" />
                    </svg>
                  </PopoverTrigger>
                  <PopoverContent className="w-56">
                    <div>View</div>
                    <div>Edit</div>
                    <div>Delete</div>
                    <div>Mark as paid</div>
                  </PopoverContent>
                </Popover>
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="font-medium">INV002</TableCell>
              <TableCell>02/01/2023</TableCell>
              <TableCell>06/01/2023</TableCell>
              <TableCell>
                <span className="inline-block bg-yellow-200 text-yellow-800 px-2 py-1 rounded-full text-xs font-medium dark:bg-yellow-700 dark:text-yellow-200">
                  Pending
                </span>
              </TableCell>
              <TableCell className="text-right">
                <input
                  className="border rounded-md p-1 text-right dark:bg-gray-800 dark:text-gray-200"
                  defaultValue="$150.00"
                  type="text"
                />
              </TableCell>
              <TableCell className="text-right">
                <Popover>
                  <PopoverTrigger>
                    <svg
                      className=" h-5 w-5 text-gray-500 hover:text-gray-700 dark:hover:text-gray-300"
                      fill="none"
                      height="24"
                      stroke="currentColor"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      viewBox="0 0 24 24"
                      width="24"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <circle cx="12.1" cy="12.1" r="1" />
                    </svg>
                  </PopoverTrigger>
                  <PopoverContent className="w-56">
                    <div>View</div>
                    <div>Edit</div>
                    <div>Delete</div>
                    <div>Mark as paid</div>
                  </PopoverContent>
                </Popover>
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="font-medium">INV003</TableCell>
              <TableCell>03/01/2023</TableCell>
              <TableCell>07/01/2023</TableCell>
              <TableCell>
                <span className="inline-block bg-red-200 text-red-800 px-2 py-1 rounded-full text-xs font-medium dark:bg-red-700 dark:text-red-200">
                  Overdue
                </span>
              </TableCell>
              <TableCell className="text-right">
                <input
                  className="border rounded-md p-1 text-right dark:bg-gray-800 dark:text-gray-200"
                  defaultValue="$350.00"
                  type="text"
                />
              </TableCell>
              <TableCell className="text-right">
                <Popover>
                  <PopoverTrigger>
                    <svg
                      className=" h-5 w-5 text-gray-500 hover:text-gray-700 dark:hover:text-gray-300"
                      fill="none"
                      height="24"
                      stroke="currentColor"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      viewBox="0 0 24 24"
                      width="24"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <circle cx="12.1" cy="12.1" r="1" />
                    </svg>
                  </PopoverTrigger>
                  <PopoverContent className="w-56">
                    <div>View</div>
                    <div>Edit</div>
                    <div>Delete</div>
                    <div>Mark as paid</div>
                  </PopoverContent>
                </Popover>
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
        <div className="flex items-center justify-between p-4">
          <div className="flex items-center space-x-2">
            <Button aria-label="Go to the previous page" variant="outline">
              <svg
                className=" h-5 w-5"
                fill="none"
                height="24"
                stroke="currentColor"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                viewBox="0 0 24 24"
                width="24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path d="m15 18-6-6 6-6" />
              </svg>
            </Button>
            <Button aria-label="Go to the next page" variant="outline">
              <svg
                className=" h-5 w-5"
                fill="none"
                height="24"
                stroke="currentColor"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                viewBox="0 0 24 24"
                width="24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path d="m9 18 6-6-6-6" />
              </svg>
            </Button>
          </div>
          <div>
            <span className="text-sm text-gray-700 dark:text-gray-300">Page 1 of 10</span>
          </div>
        </div>
      </div>
    </div>
  )
}
