/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/N77JdpNRF9N
 */
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import {
  SelectValue,
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select,
} from '@/components/ui/select';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';

export function ITRequestForm() {
  return (
    <div className="p-32">
      {/* <Card className="p-32 space-y-8 bg-slate-800"> */}
      <Card className="p-32 space-y-8 bg-neutral-900">
        <div className="space-y-2">
          <h2 className="text-3xl font-bold text-white">IT Request Form</h2>
          <p className="text-white">
            Please fill out the form below to submit your request.
          </p>
        </div>
        <div className="space-y-4">
          <div className="space-y-2">
            <Label className="text-white" htmlFor="name">
              Name
            </Label>
            <Input
              id="name"
              minlength="3"
              placeholder="Enter your full name"
              required
            />
          </div>
          <div className="space-y-2">
            <Label className="text-white" htmlFor="email">
              Email
            </Label>
            <Input id="email" placeholder="Enter your email" type="email" />
          </div>
          <div className="space-y-2">
            <Label className="text-white" htmlFor="address">
              Address
            </Label>
            <Input id="address" placeholder="Enter your address" />
          </div>
          <div className="space-y-2">
            <Label className="text-white" htmlFor="telephone">
              Telephone
            </Label>
            <Input id="telephone" placeholder="Enter your telephone number" />
          </div>
          <div className="space-y-2">
            <Label className="text-white" htmlFor="country">
              Country
            </Label>
            <Select>
              <SelectTrigger id="country">
                <SelectValue placeholder="Select a country" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="usa">USA</SelectItem>
                <SelectItem value="uk">UK</SelectItem>
                <SelectItem value="canada">Canada</SelectItem>
                <SelectItem value="australia">Australia</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-2">
            <Label className="text-white" htmlFor="problem-category">
              Problem category
            </Label>
            <Select>
              <SelectTrigger id="problem-category">
                <SelectValue placeholder="Select a problem category" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="computer">Computer</SelectItem>
                <SelectItem value="email">Email</SelectItem>
                <SelectItem value="network">Network</SelectItem>
                <SelectItem value="phone">Phone</SelectItem>
                <SelectItem value="other">Other</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-2">
            <Label className="text-white" htmlFor="issue-date">
              Date of Issue
            </Label>
            <Input id="issue-date" type="date" />
          </div>
          <div className="space-y-2">
            <fieldset>
              <legend className="font-medium text-white">
                Is the Issue preventing you from doing anything?
              </legend>
              <div className="flex space-x-4">
                <div>
                  <input id="yes" name="issue" type="radio" />
                  <label className="ml-2 text-white" htmlFor="yes">
                    Yes
                  </label>
                </div>
                <div>
                  <input id="no" name="issue" type="radio" />
                  <label className="ml-2 text-white" htmlFor="no">
                    No
                  </label>
                </div>
              </div>
            </fieldset>
          </div>
          <div className="space-y-2">
            <fieldset>
              <legend className="font-medium text-white">
                Operating system
              </legend>
              <div className="flex flex-wrap space-x-4">
                <div>
                  <input id="windows-10" name="os" type="radio" />
                  <label className="ml-2 text-white" htmlFor="windows-10">
                    Windows 10
                  </label>
                </div>
                <div>
                  <input id="windows-11" name="os" type="radio" />
                  <label className="ml-2 text-white" htmlFor="windows-11">
                    Windows 11
                  </label>
                </div>
                <div>
                  <input id="mac-os" name="os" type="radio" />
                  <label className="ml-2 text-white" htmlFor="mac-os">
                    Mac OS
                  </label>
                </div>
                <div>
                  <input id="linux" name="os" type="radio" />
                  <label className="ml-2 text-white" htmlFor="linux">
                    Linux
                  </label>
                </div>
              </div>
            </fieldset>
          </div>
          <div className="space-y-2">
            <Label className="text-white" htmlFor="issue-description">
              Please explain the issue you're experiencing
            </Label>
            <textarea
              className="w-full h-24 px-3 py-2 border border-gray-300 rounded-md dark:border-gray-600 dark:bg-gray-800 dark:text-white"
              id="issue-description"
              placeholder="Describe your issue..."
              required
            />
          </div>
          <div className="space-y-2">
            <Label className="text-white" htmlFor="file-upload">
              Upload a file
            </Label>
            <div className="w-full py-2 px-3 rounded-md border-2 border-dashed border-zinc-500 dark:border-zinc-400">
              <input
                className="w-full text-white bg-slate-800"
                id="file-upload"
                type="file"
              />
            </div>
          </div>
          <Button className="w-full" type="submit">
            Submit Request
          </Button>
        </div>
      </Card>
    </div>
  );
}
